// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentinelBackend.Infrastructure.Persistence;

#nullable disable

namespace SentinelBackend.Infrastructure.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    partial class SentinelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelBackend.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LatestStateDeviceId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("LatestStateDeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SentinelBackend.Domain.Entities.LatestDeviceState", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("CycleCount")
                        .HasColumnType("int");

                    b.Property<bool?>("HighWaterAlarm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("PanelVoltage")
                        .HasColumnType("float");

                    b.Property<double?>("PumpCurrent")
                        .HasColumnType("float");

                    b.Property<int?>("RuntimeSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("SignalRssi")
                        .HasColumnType("int");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DeviceId");

                    b.ToTable("LatestDeviceStates");
                });

            modelBuilder.Entity("SentinelBackend.Domain.Entities.Device", b =>
                {
                    b.HasOne("SentinelBackend.Domain.Entities.LatestDeviceState", "LatestState")
                        .WithMany()
                        .HasForeignKey("LatestStateDeviceId");

                    b.Navigation("LatestState");
                });
#pragma warning restore 612, 618
        }
    }
}
